### ISSUE TITLE
F3D does not start anymore since last update

### ISSUE THREAD

**Issue by frederik-elwert** [flathub/io.github.f3d_app.f3d#36]
Since the last update e23350906aa18eefe268aab19f3b8c572018579a23f7fb79b4c7715e89f3828a (2023-07-03) F3D does not start any more on my Ubuntu 22.04 system.

When I revert the change (`sudo flatpak update --commit=e9eda45b2e304bbde03b52fd2f451b2faae4fbf63e0f10e375faeeb2d8bce25d io.github.f3d_app.f3d`), then it starts again.

I don’t get any error message, and I don’t know if this is an upstream or packaging issue. I’m happy to provide more information, but I’d need a little guidance, since I’m new to flatpak.

**Comment by kevinsmia1939** [comment]
Hi,
try running this command

`flatpak run io.github.f3d_app.f3d`

**Comment by frederik-elwert** [comment]
I did, but it immediately returned, prints nothing, and the app doesn't show.

**Comment by kevinsmia1939** [comment]
try this
`flatpak run --command=bash io.github.f3d_app.f3d`
then type `f3d` and press enter

**Comment by frederik-elwert** [comment]
Thanks for the help! I tried again, and now the app launches without problems. There was also a Flatpak update for the nvidia GL driver, maybe that was the actual issue. Sorry for the noise.
